################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
footer_content = "Chinese Genomics Meet-up online (CGM) was launched by several early-career scientists in January 2017. The goal of CGM is to promote communication and cooperation among researchers whose primary research interest focuses on genomics. CGM is a weekly online event, primarily delivered in the Chinese language. You can follow us by subscribing to our WeChat Group or follow us on this website, YouTube Channel, or Bilibili. We welcome undergraduate, graduate students, postdocs, and faculty working on Molecular Biology, Genetics, Genomics, Bioinformatics, Biostatistics, and Evolutionary Biology."
# copyright
copyright = "Copyright by CGM"

################################### Chinese language #####################################
[zh]
languageName = "Ch"
languageCode = "zh-zh"
contentDir = "content/chinese"
weight = 2
footer_content = "华人基因组学在线沙龙 (CGM)，由北美从事基因组学研究的青年华人学者于 2017 年 1 月份发起。旨在增进从事基因组学研究的华人之间的交流、学习和合作。论坛按照亚太，美洲，和欧洲三个时区轮流举办，每次邀请一到两位学者就自己的研究课题进行学术汇报。汇报主要以中文的形式在 YouTube Channel 或者 bilibili 网站直播或录播。欢迎从事分子生物学、遗传学、基因组学、生物信息学、生物统计学、进化生物学相关领域的华人同学（包括本、硕、博和博后）和老师参与。"
# copyright
copyright = "Copyright by CGM"

################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore dolore magna aliquyam eratnonumy onsetetur"
# copyright
copyright = "Copyright by your company"