################################### Chinese language #####################################
[en]
languageName = "Ch"
languageCode = "zh-zh"
contentDir = "content/chinese"
weight = 1
footer_content = "华人基因组学在线沙龙 (CGM)，一个501(C)非营利性组织，由北美从事基因组学研究的青年华人学者于 2017 年 1 月份发起。旨在增进从事基因组学研究的华人之间的交流、学习和合作。"
# copyright
copyright = "Copyright by CGM"

################################### English language #####################################
[zh]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
footer_content = "Chinese Genomics Meet-up (CGM), a 501(C) nonprofit organization, is a volunteer-led platform launched in 2017 to connect Chinese-speaking genomics researchers through weekly online seminars and global community engagement."
# copyright
copyright = "Copyright by CGM"
