############# Ch navigation ##############
# main menu
[[main]]
name = "首页"
url = ""
weight = 1

[[main]]
name = "关于我们"
url = "about/"
weight = 2

[[main]]
name = "学术报告"
url = "blog/"
weight = 3

[[main]]
name = "组织管理"
url = "team/"
weight = 4


[[main]]
name = "Services"
url = "services/"
weight = 5




  
[[main]]
name = "Pages"
weight = 7
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Career"
  url = "career/"

  [[main]]
  parent = "Pages"
  name = "Pricing"
  url = "pricing/"

  [[main]]
  parent = "Pages"
  name = "Pricing 2"
  url = "pricing-2/"
  
  [[main]]
  parent = "Pages"
  name = "How It Works"
  url = "how-it-works/"
  
  [[main]]
  parent = "Pages"
  name = "Testimonial"
  url = "testimonial/"
  
  [[main]]
  parent = "Pages"
  name = "Faq"
  url = "faq/"
  
  [[main]]
  parent = "Pages"
  name = "Changelog"
  url = "changelog/"
  




# Footer menu
[[footer]]
name = "Faq"
url = "faq/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer]]
name = "Contact"
url = "contact/"
weight = 4

[[footer]]
name = "网站管理"
url = "admin/"
weight = 5

[[footer]]
name = "Doc"
url = "testlogin/"
weight = 6